### ISSUE TITLE
在吗，能私聊吗？

### ISSUE THREAD

**Issue by leichunanfeigh** [ZXLBoaConstrictor/ZXLRecorder#2]

**Comment by ZXLBoaConstrictor** [comment]
有什么能帮到你的？

**Comment by leichunanfeigh** [comment]
我用你的工程，不能后台录制（回到桌面）音频哦，添加了权限也不行，不知道为啥。
------------------ 原始邮件 ------------------
发件人: "zhangxiaolong"<notifications@github.com>;
发送时间: 2019年4月12日(星期五) 上午9:22
收件人: "ZXLBoaConstrictor/ZXLRecorder"<ZXLRecorder@noreply.github.com>;
抄送: "627908233"<627908233@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [ZXLBoaConstrictor/ZXLRecorder] 在吗，能私聊吗？ (#2)




有什么能帮到你的？

**Comment by ZXLBoaConstrictor** [comment]
我今天测试一下，是点开录音后，后台录制（回到桌面）音频，没有录制成功对吗？

**Comment by ZXLBoaConstrictor** [comment]
我今天做了一个简单的测试，Dome是可以后台录制成功的。我把测试的设置也提交了，希望能帮到你
