### ISSUE TITLE
转码

### ISSUE THREAD

**Issue by zhvip** [ZXLBoaConstrictor/ZXLRecorder#3]
停止录音时候，还有一部分PCM数据(<PCM_SIZE)没有进行转码而丢弃了。

**Comment by ZXLBoaConstrictor** [comment]
能不能把你分析的更具体的说一下。我抽时间处理一下

**Comment by zhvip** [comment]
你这里是每次取一个pcm_buffer的数据去转码，停止录音时候，还有部分原数据没有转码就舍弃了。比如说，我录音10.5秒，每次取1秒数据进行转码，最后的0.5秒数据因为一直没有凑够1秒就没有处理。if(length > PCM_SIZE * 2 *sizeof(short int))。我大概是这个意思
